BINARY			:= usart
DEVICE 			:= STM32F103RB
OPENOCD_FILE 	:= board/st_nucleo_f103rb.cfg
OPENCM3_DIR 	:= ../libopencm3
OBJS			+= build/usart.o
CFLAGS			+= -Os --specs=nano.specs
include ../libopencm3.mk
